Changes
Developer-Days/OpensourceChallenge pull request #4
Opened 2021-08-23 10:43 UTC by tusqasi

possibly correct some minor things

2021-08-23 11:35 UTC, amino19 requested changes

2021-08-23 11:35 UTC, amino19 commented on README.md
>  git clone
```suggestion
git clone <forked-repo-url>
```

2021-08-23 11:35 UTC, amino19 commented on README.md
> +```bash
@tusqasi : Need to remove `bash` & revert the commit here!

2021-08-23 11:35 UTC, amino19 commented on README.md
@tusqasi : Try to remove spaces below `#`, `##` & `###` :slightly_smiling_face:

2021-08-23 15:10 UTC, amino19 commented
@tusqasi : LGTM! :partying_face: 

@ghulamyazdani : Pl take this to your end!

2021-08-23 16:05 UTC, ghulamyazdani commented
@tusqasi could you please make a new branch and commit to those ? this is conflicting with the recent commit!!

2021-08-23 16:05 UTC, ghulamyazdani commented
@tusqasi could you please make a new branch and commit to those ? this is conflicting with the recent commit!!

2021-08-24 08:27 UTC, tusqasi commented
Sure. I'll close this PR then.

2021-08-24 08:27 UTC, closed without merging